apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "order.fullname" . }}
  labels:
    {{- include "order.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "order.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "order.selectorLabels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "order.fullname" . }}

      containers:
        - name: order
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command: ["java"]
          args: ["-jar", "/app/app.jar"]

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}

          envFrom:
            - configMapRef:
                name: {{ include "order.fullname" . }}-config
            - secretRef:
                name: {{ include "order.fullname" . }}-secret

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
