apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order.fullname" . }}-secret
type: Opaque
stringData:
  DB_URL: {{ .Values.secrets.dbUrl | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
