apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: store-ui
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/your-org/signalforge
    targetRevision: main
    path: charts/ui-chart
    helm:
      valueFiles:
        - ../../helm-values/store-ui.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: signalforge

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
