# Default settings for every StreamlinePay microservice
replicaCount: 1

image:
  repository: "" # Leave empty; defined per service
  tag: ""        # Leave empty; defined per service
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80       # Default port

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Global env variables (like DB host) go here
env:
  DB_HOST: "postgres-service"